### ISSUE TITLE
Duplicate Content-Length for CORS

### ISSUE THREAD

**Issue by literakl** [nanoexpress/pro#38]
I have written unit tests for my API and I realized that OPTIONS calls fails because Nanoexpress returns duplicated Content-Length header. I tried both Axios and GotJS clients. It seems that the exception is thrown inside NodeJS HTTP parser (I use NodeJS v12.16.2 now). I moved to backend and tested the same methods with NanoExpress and Express. Express test passes while Nanoexpress test fails.

Here is the repo to try it yourself: https://github.com/literakl/nano-options
Code:

```
const cors = require('cors');
app.options('/v1/users/:userId', cors());
app.options('/v1/polls/:pollId', cors(), () => {});
```

Exception:

```
RequestError: Parse Error: Duplicate Content-Length
GotError: Parse Error: Duplicate Content-Length
    at onError (node_modules\got\dist\source\request-as-event-emitter.js:140:29)
    at ClientRequest.<anonymous> (node_modules\got\dist\source\request-as-event-emitter.js:157:17)
    at ClientRequest.emit (events.js:322:22)
    at ClientRequest.origin.emit (node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)
    at Socket.socketOnData (_http_client.js:483:9)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at Socket.socketOnData (_http_client.js:476:22)
```

Curl:

```
curl -v -X options http://127.0.0.1:3000/v1/users/sdd
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
> options /v1/users/sdd HTTP/1.1
> Host: 127.0.0.1:3000
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: http://localhost:5000
< Vary: Origin
< Access-Control-Allow-Methods: GET,HEAD,PUT,PATCH,POST,DELETE
< Access-Control-Allow-Headers: Content-Type,Authorization
< Content-Length: 0
< uWebSockets: v0.17
< Content-Length: 0
<
* Connection #0 to host 127.0.0.1 left intact

```

**Comment by dalisoft** [comment]
According to [new rule](https://github.com/nanoexpress/pro/issues/44#issue-643407894), i keep issues open only if it's related to **nanoexpress**, not to it's core.
When it will be fixed on uWebSockets.js, then on this repo also will be fixed
