### ISSUE TITLE
POST Method doesn't seem to work

### ISSUE THREAD

**Issue by vmtran123** [nanoexpress/pro#42]
I am trying implement a sign up function which should take the body of the request then save it to MongoDB via mongoose. 

- NodeJS 14.3.0
- Nanoexpress-pro 1.11.4
- Mongoose 5.9.19
- bodyparser 1.19.0

app.js
```javascript
import nanoexpress from 'nanoexpress-pro';
import bodyParser from 'body-parser';
import morgan from 'morgan';
import multilang from './helpers/multilang.js';
import configRoute from './routes/auth.route.js'
import { signUp } from './controllers/auth.controller.js';

const app = nanoexpress();
if (process.env.NODE_ENV === 'development') app.use(morgan('dev'));

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json({ limit: '10kb' }));
app.use(multilang({ baseLanguage: 'en', path: './locales' }));

app.get('/test', (req, res, next) => {
  res.status(200).json({
    msg: 'ok',
  });
});

app.post('/api/v1/users/signup', signUp);

export default app;
```
auth.controller.js
```javascript
import User from '../models/user.model.js';

export const signUp = async (req, res, next) => {
  const newUser = await User.create(req.body);

  res.status(200).json({
    status: 'success',
    data: {
      user: newUser
    }
  });
};

```
In Postman, when I sent a raw request (JSON format) with blank body without the braces, the application encountered this error and got terminated immediately.
```javascript
file:///home/vmtran/demonano/node_modules/nanoexpress-pro/src/request-proto/http/body.js:13
      req.body = buffer.toString('utf8').replace(SPACE_TRIM_REGEX, '');
                        ^

TypeError: Cannot read property 'toString' of undefined
    at Readable.<anonymous> (file:///home/vmtran/demonano/node_modules/nanoexpress-pro/src/request-proto/http/body.js:13:25)
    at Object.onceWrapper (events.js:421:28)
    at Readable.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
Blank body with braces (even full body caused the same error):
```javascript
TypeError: stream.on is not a function
    at readStream (/home/vmtran/demonano/node_modules/raw-body/index.js:190:10)
    at getRawBody (/home/vmtran/demonano/node_modules/raw-body/index.js:108:12)
    at read (/home/vmtran/demonano/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/home/vmtran/demonano/node_modules/body-parser/lib/types/json.js:135:5)
    at file:///home/vmtran/demonano/node_modules/nanoexpress-pro/src/Route.js:247:17
    at new Promise (<anonymous>)
    at middleware (file:///home/vmtran/demonano/node_modules/nanoexpress-pro/src/Route.js:246:22)
    at file:///home/vmtran/demonano/node_modules/nanoexpress-pro/src/Route.js:434:38
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
POST /api/v1/users/signup - - ms - -
```
When I sent the request under form-data, I got this error:
```javascript
Singup ...
----------------------------892368869056266361266620--st be an object, got ----------------------------892368869056266361266620
    at model.Document (/home/vmtran/demonano/node_modules/mongoose/lib/document.js:92:11)
    at model.Model (/home/vmtran/demonano/node_modules/mongoose/lib/model.js:107:12)
    at new model (/home/vmtran/demonano/node_modules/mongoose/lib/model.js:4706:15)
    at /home/vmtran/demonano/node_modules/mongoose/lib/model.js:3076:22
    at /home/vmtran/demonano/node_modules/mongoose/lib/model.js:3112:7
    at Array.forEach (<anonymous>)
    at /home/vmtran/demonano/node_modules/mongoose/lib/model.js:3111:15
    at /home/vmtran/demonano/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/vmtran/demonano/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Function.create (/home/vmtran/demonano/node_modules/mongoose/lib/model.js:3046:10)
    at signUp (file:///home/vmtran/demonano/controllers/auth.controller.js:5:30)
    at routeFunction (file:///home/vmtran/demonano/node_modules/nanoexpress-pro/src/Route.js:218:32)
    at file:///home/vmtran/demonano/node_modules/nanoexpress-pro/src/Route.js:473:22
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
POST /api/v1/users/signup - - ms - -


```

**Comment by dalisoft** [comment]
Hi @vmtran123 

Thanks for using nanoexpress, but please read [about new rules](https://github.com/nanoexpress/nanoexpress/issues/108) and do these steps

1. Create repo which presents minimal function/issue
2. Use external temporarily DB (Heroku MongoDB?)
3. Replace entire snippet/part-of-code to link to your prepared repo

If you cannot these steps, this issue will be closed without any futher discussion and fixes

I hope you understand me
Thanks

Regards,
Davlik

**Comment by dalisoft** [comment]
Even better, i recommend you post on **StackOverflow** as it's not really shows bug, just like _why it doesn't work_

**Comment by dalisoft** [comment]
No response, no test repo. I'll closing this according to new rules
